{% set name = "pydataverse" %}
{% set version = "0.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d5f959735a70d2f955aa354da29f2f851406dffae915f31277cd01ae2b030c99

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - poetry
  run:
    - python >={{ python_min }}
    - httpx >=0.27.0
    - jsonschema >=4.21.1

test:
  imports:
    - pyDataverse
  commands:
    - pip check
  requires:
    - pip
    - poetry
    - python {{ python_min }}

about:
  home: https://github.com/gdcc/pyDataverse
  summary: A Python module for the Dataverse APIs and its data-types
  license: MIT
  license_file: LICENSE.txt
  doc_url: https://pydataverse.readthedocs.io
  dev_url: https://github.com/gdcc/pyDataverse

extra:
  recipe-maintainers:
    - PennyHow
    - izahn
    - pdurbin
