{% set name = "pydataverse" %}
{% set version = "0.3.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3cc3750211cbece3a309a99e2a3f26622b83071e2e4ebd9d1d5e8e88f593974e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - poetry
  run:
    - python >={{ python_min }}
    - httpx >=0.27.0
    - jsonschema >=4.21.1

test:
  imports:
    - pyDataverse
  commands:
    - pip check
  requires:
    - pip
    - poetry
    - python {{ python_min }}

about:
  home: https://github.com/gdcc/pyDataverse
  summary: A Python module for the Dataverse APIs and its data-types
  license: MIT
  license_file: LICENSE.txt
  doc_url: https://pydataverse.readthedocs.io
  dev_url: https://github.com/gdcc/pyDataverse

extra:
  recipe-maintainers:
    - PennyHow
    - izahn
    - pdurbin
